Dara Frames


```{r}
View(mtcars)


```
creating a data fram

```{r}
name <- c("Mercury", "Venus", "Earth", "Mars", "Jupiter", "Saturn", "Uranus", "Neptune")
type <- c("Terrestrial planet", "Terrestrial planet", "Terrestrial planet", 
          "Terrestrial planet", "Gas giant", "Gas giant", "Gas giant", "Gas giant")
diameter <- c(0.382, 0.949, 1, 0.532, 11.209, 9.449, 4.007, 3.883)
rotation <- c(58.64, -243.02, 1, 1.03, 0.41, 0.43, -0.72, 0.67)
rings <- c(FALSE, FALSE, FALSE, FALSE, TRUE, TRUE, TRUE, TRUE)

plantes_df <- data.frame(name, type, diameter, rotation, rings)
plantes_df
```
selection of data frame elements

```{r}
plantes_df[1,3]
plantes_df[4,]
plantes_df[1:5,"diameter"]


rings_vectpr <- plantes_df$rings

plantes_df[!rings_vectpr,]

subset(plantes_df, subset=diameter<1)



```

sorting

```{r}

a <- c(100,10,1000)
order(a)
a[order(a)]

positions <- order(plantes_df$diameter)
positions

plantes_df[positions,]

```

List

```{r}
my_vector <- 1:10
my_matrix <- matrix(1:9, ncol=3)
my_df <- mtcars[1:10,]

my_list <- list(my_vector, my_matrix, my_df)

my_list

names (my_list) <- c("vec", "mat", "df")
my_list
```

```{r}
mov <- c("The Shining")
act <- matrix(c("Jack Nicholson","Shelley Duvall","Danny Lloyd","Scatman Crothers","Barry Nelson"))

scores <- c(4.5,5,4)
sources <- c("IMDb1","IMDb2","IMDb3")
comments <- c("Best Horror Film I Have Ever Seen","A truly brilliant and scary film from Stanley Kubrick","A masterpiece of psychological horror")
rev <- data.frame(scores, sources, comments)

shining_list <- list(moviename = mov, actor=act, reviews=rev)
shining_list

```
selecting
```{r}
shining_list[[2]][1]


```

