

```{r}
library("gapminder")
library("dplyr")

gapminder
```

Filtering for one year

```{r}
gapminder %>%
  filter(year==1957)


```
Filtering for one country and one year

```{r}
gapminder %>%
  filter(year==1957, country == "China")


```
Arranging observation by life expectancy 

```{r}
gapminder %>%
  arrange(lifeExp)


# Sort in Descendin order of lifeExp

gapminder %>%
  arrange(desc(lifeExp))

```
Filtering and arranging

```{r}
gapminder %>%
  filter(year ==)


```
Using mutate to change or create a column

```{r}
#Use mutate to change lifeExp to be in months

gapminder %>%
  mutate(lifeExp == 12*lifeExp)

# Use mtate to create a new colum callder lifeExpMonths
gapminder %>%
  mutate(lifeExpMonths = 12*lifeExp)
```
Combining filter, mutate and arrange

```{r}
gapminder %>%
  filter(year==2007) %>%
  mutate(lifeExpMonths = 12*lifeExp) %>%
  arrange(desc(lifeExpMonths))


```
Visualizing with ggplot2

```{r}

gapminder_1925 <- gapminder %>%
  filter(year ==1952)

library(ggplot2)

ggplot(gapminder_1925, aes(x=pop, y=gdpPercap)) +
  geom_point()

```
```{r}
ggplot(gapminder_1925, aes(x=pop, y=lifeExp)) +
  geom_point()
```

```{r}
gapminder_1925 <- gapminder %>%
  filter(year==1952)

ggplot(gapminder_1925, aes(x=pop,y=lifeExp))+
  geom_point() +
  scale_x_log10()



```
```{r}
ggplot(gapminder_1925, aes(x=pop,y=gdpPercap)) +
  geom_point() +
  scale_x_log10() +
  scale_y_log10()
```
Adding color to a scatter plot

```{r}
ggplot(gapminder_1925, aes(x=pop,y=lifeExp,color=continent)) +
  geom_point() +
scale_x_log10()
```
Adding size and color to a plot

```{r}
ggplot(gapminder_1925, aes(x=pop,y=lifeExp,color=continent, size=gdpPercap)) +
  geom_point() +
scale_x_log10()
```
Faceting

Creating a subgraph for each continent

```{r}
gapminder_1925

ggplot(gapminder_1925, aes(x=pop,y=lifeExp)) +
  geom_point() +
scale_x_log10() +
  facet_wrap(~ continent)

```
Faceting by year

```{r}

ggplot(gapminder, aes(x=gdpPercap,y=lifeExp,color=continent,size=pop)) +
  geom_point() +
scale_x_log10() +
  facet_wrap(~ year)
```


