Equality

```{r}
"Rchitect" != "rchitect"
TRUE == FALSE
-6 * 14 !=17 - 101
TRUE == 1

-6*5+2 >= -10 +1
"raining" <= "raining dogs"
TRUE < FALSE
```
Compare vectors
```{r}

linkedin <- c(16,9,13,5,2,17,14)
facebook <- c(17,9,16,5,2,13,14)

linkedin > 15
facebook <= 5

linkedin > facebook
```
compare matrices

```{r}
views <- matrix(c(linkedin,facebook), nrow=2, byrow=TRUE)
views

views == 13
views <= 14
```

& and 


```{r}
linkedin
last <- tail(linkedin, 1)



last > 5 | last <10
last > 15 & last <=20

linkedin > 10 & facebook <10
linkedin <= 12 |  facebook >= 12
```
the if statement

```{r}
medium <- "linkedin"
num_views <- 14

if(medium == "Linkedin"){
  print ("showing Linkedin information")
  
}else if (medium == "Facebook"){
  print("Showing facebook information")
} else {
  print("unkowns medium")
}


if(num_views >15){
  print("you are popular")
  
}else if (num_views <=15 & num_views >10) {
  
  Pirnt ("your number of views is average")
} else {
  print("try to be more visible")
}
```

```{r}
result <- ""
number <-101

if (number <10){
  if(number<5){
    result <- "extra small"
  }
  else{
    result <- "small"
  }
}else if (number <100){
  result <- "medium"
}else {
  result <- "large"
}
print(result)

```
write a while loop

```{r}
speed <- 64

while (speed >30){
  print("slow down")
  speed <- speed - 7
  
  
  
}

speed


```

```{r}

while (speed >30){
  print(paste("your speed is", speed))
  if(speed >= 48){
    print("slow down big time!")
    speed <- speed - 11
  }else{
    print("slow down!")
    speed <- speed - 6
  }
}
speed
```
stop the while loop: Break


```{r}

speed <- 88

while (speed >30){
  print(paste("Your speed is", speed))
  
  if (speed > 80){
    break
  }
  
  if(speed > 48){
    print("slow down big time!")
    speed <- speed -11
  }else {
    print("slow dowsn")
    speed <- speed -6
  }
}



```

Build a while loop from scratch

```{r}
i <- 1

while(1 <= 10){
  print(3*i)
  if((i*3) %% 8 == 0){
    break
  }
  i < i+1
}



```
loop over a vecctor 

```{r}
linkedin <- c(16,9,13,5,2,17,14)


for (l in linkedin){
  print (l)
  
}

for (i in 1: length(linkedin)){
  print(linkedin[i])
  
}

```
loop over a list

```{r}

nyc <- list(pop = 8405837, broughs = c("manhatan","Brooklyn","Queen","Staten island"), Capital = FALSE)

for (n in nyc){
  print(n)
  
}

for (i in 1:length(nyc)){
  print(nyc[1])
  
}

```

Loop over a matrix

```{r}
new_hope <- c(460.998,314.4)
empire_strikes <- c(290.475,247.900)
return_jedi <- c(309.306,165.8)

box_office <- c(new_hope, empire_strikes, return_jedi)
box_office

star_wars_matrix <- matrix(box_office, byrow = TRUE, nrow = 3)
star_wars_matrix

```
```{r}
for (i in 1:nrow(star_wars_matrix)){
   for (i in 1:ncol(star_wars_matrix)){
     print(paste("on row", i, "and colum", j, "the board contains", star_wars_matrix[i,j]))
   }
  
}


```
```{r}
linkedin <- c(16,9,13,5,2,17,14)

for (li in linkedin){
  if(li >10){
    print("you are popular!")

  }
  else{
    print ("Be more visible!")
  }
  
  if(li>16){
    print(("this ridiculous im outta here!"))
    break
    
  }
  if(li>5){
    print("this is too embarrasing")
    
  }
  print(li)
}


```

